name: Major Release

on:
  workflow_dispatch:
    inputs:
      version:
        description:
          'The version override. Example: "8.1.2". Leave blank if you want conventional commits to
          decide which version'

jobs:
  release-major:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0 # Needed to do a proper push

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: support
          tags: true

      - name: Get previous tag
        id: previous-tag
        run: echo "::set-output name=tag::$(node -p 'require("./lerna.json").version')"

      - name: Pull changes >> prerelease/major -> master
        run: git pull origin prerelease/major

      - uses: Workday/canvas-kit-actions/install@v1
        with:
          node_version: 16.x

      - uses: Workday/canvas-kit-actions/release@test-release
        with:
          gh_token: ${{ secrets.GITHUB_TOKEN }}
          gh_rw_token: ${{ secrets.GH_RW_TOKEN }}
          publish_token: ${{ secrets.NPM_CI_PUBLISH_TOKEN }}
          chromatic_project_token: ${{ secrets.CHROMATIC_APP_CODE }}
          version: 'major'
          toRef: 'prerelease/major'

      - name: Checkout prerelease/major
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0 # Needed to do a proper push
          ref: prerelease/minor

      - name: Pull changes >> master -> prerelease/minor
        run: git pull origin master --no-edit

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: prerelease/minor
          tags: true

      - name: Checkout prerelease/major
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0 # Needed to do a proper push
          ref: prerelease/major

      - name: Pull changes >> prerelease/minor -> prerelease/major
        run: git pull origin prerelease/minor --no-edit

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: prerelease/major
          tags: true

      - name: Update support dist tag
        run: node utils/dist-tag.mjs
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_CI_PUBLISH_TOKEN }}
          DIST_TAG: 'support'
          VERSION: ${{ steps.previous-tag.outputs.tag }}
          ACTION_TYPE: 'update'
